### ISSUE TITLE
C++ operator sugar - add std::string & wstring operators

### ISSUE THREAD

**Issue by cztomczak** [udp/json-parser#13]
Hi,

People using C++ wrapper will most definitely want to use c++ strings. What do you think of adding std::string & std::wstring operators?

In my project I've added this code and it's very useful:

         #ifdef __cplusplus

               #include <string.h>
               #include <string>

         ...

         inline operator std::string () const
         {
            switch (type)
            {
               case json_string:
                   return std::string(u.string.ptr);

               default:
                   return "";
            }
         }

         inline operator std::wstring () const
         {
            std::string string;
            switch (type)
            {
               case json_string:
                  string = u.string.ptr;
                  break;
            }
            return Utf8ToWide(string);
         }

Function Utf8ToWide() is windows only:

    #include <windows.h>

    std::wstring Utf8ToWide(const std::string& utf8String) {
        int requiredSize = MultiByteToWideChar(CP_UTF8, 0, utf8String.c_str(), -1, 
                                               0, 0);
        wchar_t* wideString = new wchar_t[requiredSize];
        int copiedCharacters = MultiByteToWideChar(CP_UTF8, 0, utf8String.c_str(),
                -1, wideString, requiredSize);
        std::wstring returnedString(wideString);
        delete[] wideString;
        return returnedString;
    }

For cross-platform conversion there is mbstowcs() function:
http://www.cplusplus.com/reference/cstdlib/mbstowcs/

But I've read there are some problems when using mbstocws() on Windows, seems that it depends on current locale, see this topic:

http://www.gamedev.net/topic/443913-what-is-different-between-multibytetowidechar-and-mbstowcs/

> Taking a quick look in VC8's CRT source, it appears mbstowcs calls 
> MultiByteToWideChar. However, it's only doing so when the current locale 
> is changed from the default locale. So I'm guessing the default locale is the
>  C-locale, and conversion from multibyte to wide character is a simple char 
> to wchar_t assignment. Consistent with what you present.

So maybe for windows use this specific code and for other platforms mbstowcs()?

Czarek.

**Comment by udp** [comment]
Sorry for the late reply.  My problems with this:

1.  It would drag STL into anything that includes json.h, and quite a few projects use C++ without STL.  I suppose this could be avoided with an ifdef.

2. The wide string conversion is way out of the scope of the parser as a library.

Maybe you could define a std::string conversion outside of json_value instead?

**Comment by udp** [comment]
Closing old issues...
