### ISSUE TITLE
Dead store (found by scan-build)

### ISSUE THREAD

**Issue by peterhull90** [udp/json-parser#47]
Using scan-build (based on clang 3.5) it reports a dead assignment at line 653:
```C
 if ( (++ state.ptr) == end)
 {
  b = 0; <-- HERE
  break;
 }
```
It's a very minor point... but we expect perfection these days :wink: ... also just to check this is correct because the code jumps through a couple of `break`s here and it might not be doing what you expect.

**Comment by udp** [comment]
Going to leave this - it's just there to be explicit that b should be set to 0 at this point.  Thanks though!
