### ISSUE TITLE
Portability issue on pebble

### ISSUE THREAD

**Issue by wdoganowski** [udp/json-parser#49]
I want to use json-parser on pebble, but I get compilation error:

```
json.c:49:4: error: array subscript has type 'char' [-Werror=char-subscripts]
```

Following comments on http://stackoverflow.com/questions/10186219/array-subscript-has-type-char I needed to cast the parameter on (unsigned char):

```
   if (isdigit((unsigned char)c))
      return c - '0';
```

I needed to repeat it in four places.

Is there any other solution?

**Comment by udp** [comment]
That solution looks fine.  If you open a PR I'll merge it.

**Comment by DimitriPapadopoulos** [comment]
`isdigit` expects `int`, not `unsigned char`. See #120 for a variant.
