### ISSUE TITLE
Integer Overflow when supplied large number.

### ISSUE THREAD

**Issue by kcm1700** [udp/json-parser#52]
Since any signed integer overflow leads to undefined behavior in C, there should be some checks before adding and multiplication.

For example, the following codes lead to integer overflows.

``` c
json_parse("123456789012345678901234567890", 30);
json_parse("123456789012345678901234567890e1", 32);
json_parse("1e234567890123456789012345678901", 32);
```

My suggestion is to switch from `json_integer` to `json_double` type when overflow is about to happen.

For example, the following code may be used for checking integer overflow.

``` c
if ((INT64_MAX - (b-'0')) / 10 < top->u.integer)
{
    /* TODO: do something to switch to json_double type */
}
```

There are three places related to the issue.

``` c
num_e = (num_e * 10) + (b - '0');
top->u.integer = (top->u.integer * 10) + (b - '0');
num_fraction = (num_fraction * 10) + (b - '0');
```

**Comment by udp** [comment]
Sorry for the late reply.  You're absolutely right - I'll look into this in the next week or so.

**Comment by tmegow** [comment]
@xoarinn thank you for that patch, it works!

**Comment by udp** [comment]
Merged - sorry for the delay, and thanks!
