### ISSUE TITLE
Bug in float numbers reading

### ISSUE THREAD

**Issue by Arcady27** [udp/json-parser#64]
Bug while reading numbers without floating point as *dbl* values:
```c
char string[10] = "{\"a\":10}";
json_char *json;
json = (json_char*)string;
json_value *value = json_parse(json, 8);
double float_value = value->u.object.values[0].value->u.dbl;
printf("%f",  float_value);
```
In this case the read value is 0.0 instead of 10.0. But if in the JSON file 10.0 is written, then the reading is correct (with adjusting length from 8 to 10).

**Comment by udp** [comment]
Notice that the type field is json_integer in this case, not json_double.  Reading any type other than as specified in the type field is undefined behaviour, as the different value types are a union.

**Comment by Arcady27** [comment]
Yes, I see, but it will be useful if *dbl* would support integers also, because sometimes there are JSON files where generally all numbers are floats but some numbers are rounded to int values and written without floating points (in my case I met such situation while parsing XGBoost decision trees)

**Comment by udp** [comment]
To put the integers in both the integer and dbl field would require moving one of them out of the union, because in the union they share the same memory.  I guess we could do that as a compile time option.

Meanwhile, it's pretty straightforward to write a helper function like

     double jsonDouble(json_value *val) {
         if(val->type == json_double)
             return val->u.dbl;
         if(val->type == json_integer)
            return val->u.integer;
        return 0;
    }

**Comment by udp** [comment]
Closing this because it isn't a bug, but feel free to open a new issue for the feature request.
