### ISSUE TITLE
This looks awesome ..Can this be used with an array of struct ? If so how ?

### ISSUE THREAD

**Issue by denden4444** [udp/json-parser#76]
Hello there 

This looks like a gem of a parser.
I would really like to know if this can be used for serializing an array of struct and possibly how to use this on an esp8266 ?

Kind regards
Den

**Comment by LB--** [comment]
For serialization, you can use [json-builder](https://github.com/udp/json-builder). Both libraries work together and are intended to compile under an ANSI C compiler, so it should in theory be possible to use with the device you mention.
