### ISSUE TITLE
This library supports unicode characters? For Example "\u000"

### ISSUE THREAD

**Issue by PoojaRohite** [udp/json-parser#79]

**Comment by udp** [comment]
Yes

**Comment by PoojaRohite** [comment]
But in my case it was not working. Parsing gave some different result when input json is contains unicode character.

**Comment by udp** [comment]
Do you have an example?

**Comment by DimitriPapadopoulos** [comment]
Note that "`\u000`" is not a valid Unicode character, try with `\u0000`.

See [RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259):
>  Any character may be escaped.  If the character is in the Basic Multilingual Plane (U+0000 through U+FFFF), then it may be represented as a six-character sequence: a reverse solidus, followed by the lowercase letter u, followed by four hexadecimal digits that encode the character's code point.
