### ISSUE TITLE
How to form JSON response using this library? Is it necessary to read json from file or we can just use json_object_new and json_object_push methods?

### ISSUE THREAD

**Issue by PoojaRohite** [udp/json-parser#81]
build json using json_object_push and json_object_new but it has memory leak even though Json_free_value function is called at the end.

**Comment by owziga** [comment]
You can use `json_object_new` and `json_object_push`. You can see an example [issue #4](https://github.com/udp/json-builder/issues/4#issue-44886542)

**Comment by PoojaRohite** [comment]
Thank you for the reply! It works well!
